volumes:
  my_react:
services:
  demo_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kolbasa2489
      - POSTGRES_DB=demo_db
    volumes:
      - my_react:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - demo_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://demo_db:5432/demo_db'
      JAVA_OPTS: 'Xmx512m'